### ISSUE TITLE
Icon Cutter appears to not be properly applying `version` to cut .dmi files.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/icon-cutter#11]
Related issue: https://github.com/tgstation/IconDiffBot/issues/72
Cut using the wallening as well as confirmed with the /tg/ table smoothing .yaml formats.
Cut .dmi files appears to not have their version variable, which results in icon_diff_bot refusing to display it.
It's possibly related to some other oddities but this one at least is consistant based on the comments in the linked issue.

**Comment by out-of-phaze** [comment]
Might be fixed by updating https://github.com/spacestation13/dmi-rust to 0.1.2.

**Comment by ZeWaka** [comment]
Looks fixed with #12
